name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # Build and push Docker image using Docker container action
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: laila22/node-app
          tag_with_ref: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Pull and run Docker image using Docker container action
      - name: Pull and Run Docker Container
        uses: docker://laila22/node-app
        with:
          env:
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          ports:
            - "4000:4000"
          name: nodejs-app-container
